# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"

# Code of Conduct Generator
gem "net-http"
gem "fileutils"

# Email Autolinker
gem "rinku"

group :jekyll_plugins do
	gem "jekyll-redirect-from"
	gem "jekyll-seo-tag"
	gem "jekyll-sitemap"
  gem "jekyll-titles-from-headings"
  # gem "jekyll-autolink_email"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?


gem "webrick", "~> 1.8"
